### ISSUE TITLE
请教一下，我用群晖自带的数据库，注册的时候点击没反应

### ISSUE THREAD

**Issue by jjss520** [uhziel/yireader#28]
今天突然发现容器里环境的MONGODB_URI，然后照着地址，修改成群晖自带的DB，网页能正常打开但添加书源会让注册，但点击注册无反应，数据库里也没有任何数据，是不是要先导入数据模板
请教一下

mongodb://root:dai123456@127.0.0.1:3306/yireader?authSource=admin&retryWrites=true&w=majority

**Comment by zml9640** [comment]
mongodb版本不读吧， 可以分享一下能用的书源吗

**Comment by uhziel** [comment]
可以尝试先点击网页上的退出按钮，再重新登陆。不需要提前导入数据模版，数据库是空的也行。

如果上面的操作不行，可能是你群晖自带的MONGODB版本太低，并不被支持。

**Comment by jjss520** [comment]
原来是db5，我换成了db10也一样
在db10里新建了yireader库，我这样写没错吧
mongodb://root:XXXXX@127.0.0.1:3307/yireader?authSource=admin&retryWrites=true&w=majority

MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
yireader server closed
Monogodb connection closed
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
This process is pid 1
Listen on port 3001!

这是日志，麻烦给看看是哪里的问题

**Comment by jjss520** [comment]
好像是mongodb和mysql是两个东西，汗，群晖自带的是MYSQL

**Comment by jacklaplace** [comment]
等待的时间，可以看看别人的帖，我用的源在这里
https://github.com/uhziel/yireader/issues/14
