### ISSUE TITLE
Yireader 无法新部署（已部署成功的尚可运行）

### ISSUE THREAD

**Issue by Chengregnarok** [uhziel/yireader#36]
不知道老铁是否还在更新这个项目

出现如下报错了。。应该是mongoDB的老版本失效了。
MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:20)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)

我尝试了如下方法并未解决：
1、更新到 mongo:4.4.5 版本。问题照旧
2、更新到 mongo:latest（应该是7以上了）。出现新问题：5.0 以上版本不支持我的群晖 CPU （J4125）
3、早先部署成功的腾讯云 CentOS 7.6 64bit 版本中的运行好像没啥问题。。
4、Aliyun Ubuntu 22.04 64位 UEFI版新部署失败，倒在 docker-compose up -d，一堆反馈报错
5、群晖部署。。Error response from daemon: Bind mount failed: '/root/yireader/dbdata' does not exists（docker-compose 中途）没看懂

以上。。不知道有没有什么好的解决方案

**Comment by Chengregnarok** [comment]
晚上就来打脸了。。5、说的问题仔细阅读 docker-compose.yml 找到原因了，直接新建 dbdata 目录即可

**Comment by Chengregnarok** [comment]
更新近况。。我猜是我在阿里云上的设置有问题。在部署其他docker-compose的时候也失败了，但是腾讯云可以。
